spring:
  profiles:
    active: test

  output:
    ansi:
      enabled: always # ?? ?? ??

  application:
    name: QnA_board

#  thymeleaf:
#    cache: false
#    prefix: classpath:/templates/

  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/QnA_board?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create # DB ??? ????
    show-sql: true # SQL ?? ??


server:
  port: 8080